[workspace]
authors = ["sara-graca <saravsgraca@gmail.com>"]
channels = ["conda-forge"]
name = "statistical-vowel-analysis"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.13"
numpy = ">=1.26,<2"
pandas = ">=2.2,<3"
matplotlib = ">=3.8,<3.10"
ipykernel = ">=6.29,<7"
pyzmq = ">=25,<26"

[activation.env]
KMP_DUPLICATE_LIB_OK = "TRUE"
